### ISSUE TITLE
handling composite characters

### ISSUE THREAD

**Issue by ygrek** [yoriyuki/ucorelib#5]
Out of interest I was running the test from http://mortoray.com/2013/11/27/the-string-type-is-broken/ against ucorelib - and it failed.. Here is session (fresh from git) : 

```
# "noël";;
- : string = "noe\204\136l"
# let s = Text.of_string "noël";;
val s : UCoreLib.Text.t = <abstr>
# Text.length s;;
- : int = 5
# print_endline @@ Text.to_string @@ Text.sub s 0 3;;
noe
- : unit = ()
```

Also Text.reverse is missing - not sure how much it is needed in practice though.

**Comment by yoriyuki** [comment]
This is normal since Text does not normalize the contents automatically.  My opinion is that such conversion is better to be done explicitly.  The normalization will be provided in the future, in the separate package.

By the way, new Text (Text') is under implementation on the new branch "new-Rope".  Take a look if you want.
